### ISSUE TITLE
更新到最新版 1.3.7-R8-build1 后，服务器全部无法连接

### ISSUE THREAD

**Issue by mildnes** [shadowsocksr/ShadowsocksX-NG#65]
更新所有列表出错，试了所有的节点。路由上没有问题。老版本没问题

**Comment by mildnes** [comment]
重新卸载了之后，重新安装好了，但是全局连接服务器，打开网页是500错误，试了很多节点。。

**Comment by sjnhnp** [comment]
在终端 输入这个：/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew update && brew install pcre

**Comment by CsHeng** [comment]
系统10.11吧？我也一样的问题。ss-local启动不了，一直crach，提示ss-local 是 built for macos 10.12的。。蛋疼。
手动将ss-local link回2.4.9可以跑。

**Comment by mildnes** [comment]
@sjnhnp 我已经安装过brew了。。。不知道什么问题。我直接brew updata跟install pcre试试。

**Comment by mildnes** [comment]
@CsHeng 我的是全部都是500错误或者打不开网站，系统是10.12的。

**Comment by CsHeng** [comment]
@mildnes 好吧~那应该是另外的问题了。
10.11 会有我说的问题，于是我只能手动改到旧版本的sslocal，但是这样用不了新协议。

**Comment by mildnes** [comment]
@CsHeng 我没有用新协议，我自己的一直是老的协议，没有弄，500我查了好像是重复代理还是什么问题，老版本就没有问题。

**Comment by mildnes** [comment]
@CsHeng 你参考一下三楼的方法，我用他的方法解决了。

**Comment by CsHeng** [comment]
@mildnes 我是10.11的，不是这个问题。

**Comment by mildnes** [comment]
@CsHeng 这样啊，那么，好吧~~~

**Comment by ookangzheng** [comment]
我的Log
Process:               ss-local [915]
Path:                  /Users/USER/Library/Application Support/ShadowsocksX-NG/*/ss-local
Identifier:            ss-local
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ss-local [915]
User ID:               501

Date/Time:             2016-11-02 00:13:46.269 +0100
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        4076FA93-4DC9-CCED-12BC-B8E25366F004


Time Awake Since Boot: 260 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Users/okz/Library/Application Support/ShadowsocksX-NG/

Dyld Error Message:
  Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/USER/Library/Application Support/ShadowsocksX-NG/ss-local
  Reason: image not found

Binary Images:
       0x104373000 -        0x1043b3ff3 +ss-local (0) <CA51637C-8267-35BF-AD5C-A718C238E59F> /Users/USER/Library/Application Support/ShadowsocksX-NG/ss-local
       0x10afdf000 -        0x10b01c287  dyld (421.2) <13A9466A-2576-3ABB-AD9D-D6BC16439B8F> /usr/lib/dyld
    0x7fffa6225000 -     0x7fffa6309ff3  libcrypto.0.9.8.dylib (64) <4CB423CE-0B86-334A-9335-FEE75198024F> /usr/lib/libcrypto.0.9.8.dylib

**Comment by hand515** [comment]
pcre 更新后，确实解决了

**Comment by shelltea** [comment]
更新pcre已解决

**Comment by a694997640** [comment]
/Users/USER/Library/Application Support/ShadowsocksX-NG/ 替换该目录下得sslocal即可解决

**Comment by pengyichao** [comment]
求一个可以正常工作的 2.4.9 版 ss-local 二进制文件，我从DMG里往前拉了好几个版，结果都是 2.5.4 版

**Comment by CsHeng** [comment]
@pengyichao https://telegram.me/MacSSR 上TG群找。

**Comment by pengyichao** [comment]
@CsHeng 用你编译的2.5.6版替换后成功运行了

**Comment by CsHeng** [comment]
@pengyichao :)

**Comment by snailyou** [comment]
@ookangzheng 你碰到的问题解决了吗

**Comment by wxww2010** [comment]
@sjnhnp  在终端 输入这个：/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew update && brew install pcre  ===>MAC 10.12.1 下 能解决此问题，多谢！
